### ISSUE TITLE
meteor-tool 'throw new Error('Must throw non-empty error');'

### ISSUE THREAD

**Issue by tomtom87** [DanielDent/docker-meteor#15]
Followed instructions and have attempted to do a build, got the following output:

```
docker build -t myAppname .
Sending build context to Docker daemon 13.99 MB
Step 1 : FROM danieldent/meteor:onbuild
# Executing 6 build triggers...
Step 1 : COPY . /opt/src
Step 1 : WORKDIR /opt/src
 ---> Running in 1453ed5c1223
Step 1 : RUN meteor build .. --directory     && cd ../bundle/programs/server     && npm install     && rm -rf /opt/src
 ---> Running in a677fdb41901

/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259
                        throw new Error('Must throw non-empty error');
                              ^
Error: Must throw non-empty error
    at Object.Future.throw (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259:10)
    at Extract.<anonymous> (/tools/fs/files.js:699:42)
    at Extract.emit (events.js:117:20)
    at DirWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/tar/lib/extract.js:61:8)
    at DirWriter.emit (events.js:117:20)
    at FileWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/dir-writer.js:158:12)
    at FileWriter.emit (events.js:92:17)
    at WriteStream.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/file-writer.js:50:47)
    at WriteStream.emit (events.js:95:17)
    at WriteStream.<anonymous> (evalmachine.<anonymous>:1669:12)
    at OpenReq.Req.done (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/graceful-fs.js:141:5)
    at OpenReq.done (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/graceful-fs.js:61:22)
    at Object.oncomplete (evalmachine.<anonymous>:108:15)
The command '/bin/sh -c meteor build .. --directory     && cd ../bundle/programs/server     && npm install     && rm -rf /opt/src' returned a non-zero code: 8
```

**Comment by tomtom87** [comment]
Have found this ticket related https://github.com/meteor/meteor/issues/4178 

How much disk space do I need, so far I have 8gb. This seemed excessive maybe I am wrong

**Comment by tomtom87** [comment]
had to give up and reverse proxy with nginx. wont be continuing with meteor development :(
