### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by leonsp** [DanielDent/docker-meteor#9]
When I try to run an existing Meteor app with the given instructions, I get the error below:

```
$ docker run -it --rm -p 3000:3000 --link my_appDb:db -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost:3000" -e MY_KEY -e MY_USER my_app
/opt/bundle/programs/server/node_modules/fibers/future.js:245
                    throw(ex);
                          ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/opt/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I'm on Mac OS X with the following versions running:

```
$ node -v
v0.12.7
$ meteor --version
Meteor 1.1.0.3

$ boot2docker version
Boot2Docker-cli version: v1.7.0
Git commit: 7d89508

$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.8.1
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): d12ea79
OS/Arch (server): linux/amd64
```

I've tried `npm rebuild`, but it didn't help.

There was a related issue in an earlier version of Meteor: https://github.com/meteor/meteor/issues/3666

One of the comments suggested running this command to make sure my bcrypt binary is built for Linux rather than Mac, but I'm not sure where (locally? in the Dockerfile?):

   meteor build --architecture os.linux.x86_64

**Comment by kop** [comment]
Same here. Any update on this?

**Comment by onbjerg** [comment]
Same.

**Comment by nebulade** [comment]
I have the same issue on linux. 

```
$ node --version
v0.12.7

$ meteor --version
Meteor 1.2.0.2
```

**Comment by nebulade** [comment]
This is most probably related to https://github.com/meteor/meteor/issues/3666
